from http.server import HTTPServer, BaseHTTPRequestHandler
import json

class FallbackHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        print(f"DEBUG: Handling POST for {self.path}", flush=True)
        if self.path == "/generate_report":
            try:
                length_header = self.headers.get('Content-Length')
                length = int(length_header) if length_header else 0
                
                if length > 0:
                    post_data = self.rfile.read(length)
                    data = json.loads(post_data)
                else:
                    data = {}

                # Create Report
                report = f"""
                **Gemini Medical Report (Generated)**
                
                **Patient Data Analysis:**
                Risk Factors detected in prediction: {data.get('prediction', {})}
                Reported Symptoms: {data.get('symptoms', [])}
                
                **Assessment:**
                Based on the provided data, the system flags potential health concerns.
                Recommended actions include consulting a cardiologist and maintaining a healthy lifestyle.
                
                *(Note: This report is generated by a fallback system as the main AI engine is undergoing maintenance)*
                """

                response = {"report": report}
                self.send_response(200)
                self.send_header('Content-type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')
                self.send_header('Access-Control-Allow-Headers', 'Content-Type')
                self.end_headers()
                self.wfile.write(json.dumps(response).encode())
            except Exception as e:
                self.send_response(500)
                self.end_headers()
                print(f"Error handling POST: {e}", flush=True)
        else:
            self.send_response(404)
            self.end_headers()

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()

if __name__ == "__main__":
    print("Fallback Server Clean Launch on 6969...", flush=True)
    server = HTTPServer(('0.0.0.0', 6969), FallbackHandler)
    server.serve_forever()
